version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Chess
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgres/data
      - ./db/chess.sql:/docker-entrypoint-initdb.d/chess.sql
      - ./db/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
volumes:
  db:
    driver: local