const fetchPieces = () => {
  return [
    {
      name: 'BlackRook',
      x: 0,
      y: 0,
      isSelected: false,
    },
    {
      name: 'BlackKnight',
      x: 0,
      y: 1,
      isSelected: false,
    },
    {
      name: 'BlackBishop',
      x: 0,
      y: 2,
      isSelected: false,
    },
    {
      name: 'BlackQueen',
      x: 0,
      y: 3,
      isSelected: false,
    },
    {
      name: 'BlackKing',
      x: 0,
      y: 4,
      isSelected: false,
    },
    {
      name: 'BlackBishop',
      x: 0,
      y: 5,
      isSelected: false,
    },
    {
      name: 'BlackKnight',
      x: 0,
      y: 6,
      isSelected: false,
    },
    {
      name: 'BlackRook',
      x: 0,
      y: 7,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 0,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 1,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 2,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 3,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 4,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 5,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 6,
      isSelected: false,
    },
    {
      name: 'BlackPawn',
      x: 1,
      y: 7,
      isSelected: false,
    },
    {
      name: 'WhiteRook',
      x: 7,
      y: 0,
      isSelected: false,
    },
    {
      name: 'WhiteKnight',
      x: 7,
      y: 1,
      isSelected: false,
    },
    {
      name: 'WhiteBishop',
      x: 7,
      y: 2,
      isSelected: false,
    },
    {
      name: 'WhiteQueen',
      x: 7,
      y: 3,
      isSelected: false,
    },
    {
      name: 'WhiteKing',
      x: 7,
      y: 4,
      isSelected: false,
    },
    {
      name: 'WhiteBishop',
      x: 7,
      y: 5,
      isSelected: false,
    },
    {
      name: 'WhiteKnight',
      x: 7,
      y: 6,
      isSelected: false,
    },
    {
      name: 'WhiteRook',
      x: 7,
      y: 7,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 7,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 7,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 6,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 5,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 4,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 3,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 2,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 1,
      isSelected: false,
    },
    {
      name: 'WhitePawn',
      x: 6,
      y: 0,
      isSelected: false,
    },
  ];
};

export default fetchPieces;
